### ISSUE TITLE
[Meta] Bi-Weekly Planning Meetings

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/summit#244]
In an effort to make our meetings easier to find and join, we decided to start posting meeting info and notices on the /summit repo and do the following: 

- [x] add the collab summit planning meeting to our [public calendar](https://calendar.google.com/calendar/embed?src=linuxfoundation.org_fuop4ufv766f9avc517ujs4i0g%40group.calendar.google.com)
- [x] use the OpenJSF Zoom account for recurring meetings
- [ ] create a meetings directory and begin saving the agendas/rolling notes

@jorydotcom will open a PR to create the meetings directory; as well as update the README to reflect the new meeting info.

**Comment by WaleedAshraf** [comment]
Hi, @jorydotcom can you invite me to the new event?

**Comment by jorydotcom** [comment]
@WaleedAshraf done! you may also want to do the public calendar subscription too, though

**Comment by WaleedAshraf** [comment]
Thanks. I tried, with that calendar pings for all the events whereas I want notifications just for this one.
